AWSTemplateFormatVersion: "2010-09-09"

Description: CodePipeline Stack

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Parameters for Service
        Parameters:
          - ProjectName

Parameters:
  ProjectName:
    Type: String

Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Join
          - ""
          - - Fn::ImportValue: !Sub "s3-${ProjectName}-artifact-name"
        Type: S3
      Name: !Sub ${ProjectName}-codepipeline
      RoleArn: !Join
        - ""
        - - Fn::ImportValue: !Sub "iam-role-${ProjectName}-codepipeline-arn"
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                S3Bucket: !Join
                  - ""
                  - - Fn::ImportValue: !Sub "s3-${ProjectName}-source-name"
                S3ObjectKey: demo.zip
                PollForSourceChanges: false
              Name: Source
              Namespace: SourceVariables
              OutputArtifacts:
                - Name: SourceArtifact
              Region: ap-northeast-1
              RunOrder: 1
          Name: Source
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Join
                  - ""
                  - - Fn::ImportValue: !Sub "codebuild-project-${ProjectName}-name"
              InputArtifacts:
                - Name: SourceArtifact
              Name: Build
              Namespace: BuildVariables
              OutputArtifacts:
                - Name: BuildArtifact
              Region: ap-northeast-1
              RunOrder: 1
          Name: Build
        - Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: 1
              Configuration:
                ApplicationName: !Join
                  - ""
                  - - Fn::ImportValue: !Sub "codedeploy-application-${ProjectName}-name"
                DeploymentGroupName: !Join
                  - ""
                  - - Fn::ImportValue: !Sub "codedeploy-group-${ProjectName}-name"
              Name: Deploy
              Namespace: DeployVariables
              InputArtifacts:
                - Name: BuildArtifact
              Region: ap-northeast-1
              RunOrder: 1
          Name: Deploy
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-codepipeline

  EventBridgeIAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "codepipeline:StartPipelineExecution"
            Resource:
              - !Join
                - ""
                - - "arn:aws:codepipeline:ap-northeast-1:"
                  - !Sub "${AWS::AccountId}:"
                  - !Ref CodePipeline
      ManagedPolicyName: !Sub ${ProjectName}-eventbridge-iam-policy

  EventBridgeIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Ref EventBridgeIAMPolicy
      RoleName: !Sub ${ProjectName}-eventbridge-iam-role
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-eventbridge-iam-role

  EventBridge:
    Type: AWS::Events::Rule
    Properties:
      Description: for codepipeline
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - "Object Created"
        detail:
          bucket:
            name:
              - Fn::ImportValue: !Sub "s3-${ProjectName}-source-name"
      Name: !Sub ${ProjectName}-eventbridge-codepipeline
      State: ENABLED
      Targets:
        - Arn: !Join
            - ""
            - - "arn:aws:codepipeline:ap-northeast-1:"
              - !Sub "${AWS::AccountId}:"
              - !Ref CodePipeline
          Id: CodePipeline
          RoleArn: !GetAtt EventBridgeIAMRole.Arn
